name             'my-sonar-runner'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures my-sonar-runner'
long_description 'Installs/Configures my-sonar-runner'
version          '0.1.0'

depends          'apt'
depends          'java'
